spring:
  # 数据源配置
  shardingsphere:
    datasource:
      names: master,slave0
      master:
        # 数据源 主库
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/shaylee?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        username: root
        password: root
      slave0:
        # 数据源 从库0
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/shaylee?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        username: root
        password: root
    sharding:
      master-slave-rules:
        ds0:
          master-data-source-name: master
          slave-data-source-names: slave0
    props:
      sql.show: false
  # 缓存配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: root
    timeout: 6000ms
    lettuce:
      pool:
        # 最大空闲数
        max-idle: 300
        # 最小空闲数
        min-idle: 5
        # 连接池的最大数据库连接数。设为0表示无限制
        max-active: 1000
        # 最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: 20000ms
  # 消息队列配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: shaylee
    cache:
      connection:
        mode: connection
        size: 100
      channel:
        size: 100
        checkout-timeout: 200
    # 消费端配置
    listener:
      simple:
        concurrency: 5
        # manual:手动 ack（确认）
        acknowledge-mode: manual
        max-concurrency: 10
        prefetch: 1